permalink: /blog/:year/:title/
paginate: 20
paginate_path:  /blog/page/:num

exclude:
  - README.md

# externally hosted assets. For large files
external_assets: "https://1ed1fabde45aa32e0f1155aa7d8a86b1b5a88703.googledrive.com/host/0BxsJMhlYrb4QRTFGSHJTMTRuOEU"

# Used in <head> and RSS feed
name: "Edinburgh University Music Society"
description: "Scotland's foremost student music body since 1867. Society profile with details of concerts, community projects and membership."
url: "http://dev.eums.org.uk"

enable_analytics: false
google_analytics_id: 'UA-23280619-5'

sass:
  style: :compact

defaults:
  # All pages should use default layout
  - scope:
      path: ""
    values:
      layout: "default"

lunr_search:
  strip_index_html: true

assets:
  dirname: assets/forever
  baseurl: /assets/forever/

prose:
  siteurl: "http://eums.dev.garrood.me"
  media: "assets/img"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
